### ISSUE TITLE
colab 실행 문의

### ISSUE THREAD

**Issue by RogerHeederer** [dreamingjudith/KoGPT2-personachat#9]
안녕하세요. 개인 연구를 위해 해당 소스를 분석해보고 있는 학생입니다.

혹시 해당 코드를 코랩에서도 실행할 수 있을까요??

코랩에 anaconda 패키지를 정상적으로 설치 후, 해당 소스를 사용해보려고 여러 방법으로 시도중인데 잘 안되네요, 

1. 코랩에 아나콘다 패키지 설치 후 실행
conda activate cm을 한 후,
CUDA_VISIBLE ~~~ cm_kogpt2.py ~~ 명령어를 작성하면
No module named 'torch' 오류가 뜨는 등
진척이 되지 않아 여기에 글을 한번 남겨봅니다.

2. 코랩에서 관련 requirements.txt만 설치 후 실행 (without anaconda)

학습 실행까진 되는데, CUDA out of memory가 뜨네요.

코랩으로 적절하게 실행할 수 있는 방법이나, .ipynb 파일이 있을까요~?

오픈 소스 제공 감사드립니다!

**Comment by dreamingjudith** [comment]
안녕하세요! 우선 완성도가 떨어지는 프로젝트인데 관심 가져주셔서 감사합니다.
제가 코랩으로도 실행했던 기억이 있는데 일이 많은 회사원이라 금방 확인해드리기 어려울 것 같네요 ㅠㅠ
주말까지는 답변드릴 수 있도록 하겠습니다~

참고로 코랩에서 실행할 때는 T4 아니면 K80이 잡힐 건데요,
제가 원래 실험할 때 사용했던 환경은 V100 1대였기 때문에
코랩에서 out of memory 문제를 회피하시려면 배치 사이즈나 history size를 좀 많이 줄이셔야 될 거에요.
(이러면 성능 저하 이슈가 생길 수밖에 없긴 한데...
원래 HuggingFace에서 낸 논문 보시면 꽤 막강한 하드웨어 자원으로 학습을 했답니다...)
문제 해결하시는데 도움이 됐으면 좋겠습니다 ㅎㅎ

**Comment by RogerHeederer** [comment]
네 답변 감사드립니다!! 아직 제 역량이 부족해서 문턱에 많이 부딪히고 있는데, 다른 방법을 더 찾아보도록 하겠습니다.
현재 colab pro를 쓰고 있어서  Tesla V100-SXM2 이런 성능 정도의 GPU로 잡히곤 하네요.

추가적으로 가이드 될 만한 답변 주시면 감사드려요! 바쁘신 와중에 답변 주셔서 다시 한번 감사 인사 드립니다!

**Comment by dreamingjudith** [comment]
아 dev 브랜치에 테스트하다 만 코랩 파일이 있었네요 ㅎㅎ
코랩에서는 저는 pip로 필요 모듈을 설치한 다음에 기존에 작성했던 코드를 다 복붙한 다음에 돌리는 식으로 진행을 했었네요;
아무래도 리팩토링이 필요한 코드라 좀 깔끔하게 정리하는 데는 시간이 걸릴 거 같아요 ㅠㅠ
여튼, 요 파일 한 번 테스트해보시겠어요?

https://github.com/dreamingjudith/KoGPT2-personachat/blob/dev/cm_kogpt2_colab.ipynb

**Comment by RogerHeederer** [comment]
아이고.. 정말 감사드립니다!! 해당 코드 잘 참고해서 만들어보도록 하겠습니다. 바쁘신 와중에 찾아주셔서 감사드립니다 ^^
